### ISSUE TITLE
FPS Animaciones del Sprite

### ISSUE THREAD

**Issue by FrowsyFrog** [dalbitresb12/zion-escape#13]
### Describe el problema

Las animaciones de las entidades como la del `player` y de los `NPC` son extremadamente rápidas. Además el `player` es instanciado con su animación activada aunque esté totalmente quieto.

### Fragmentos de código

La velocidad de las animaciones podrían arreglarse con un `timer` enfocado a las animaciones.

Respecto a que el `player` empiece en movimiento, se podría solucionar colocando en su constructor un:
`this->StopAnimation()`
`

**Comment by dalbitresb12** [comment]
Tan pronto termine con la optimización de la generación del mapa junto con el movimiento de la cámara (combinándolo todo lo mío con lo de #12) investigaré sobre esto. @amenes12 @IzaYam podrían también investigar sobre esto y abrir su propio PR. No olviden asignarse este Issue si estarán trabajando en este problema.

_¡Gracias por el reporte, @FrowsyFrog!_
