### ISSUE TITLE
Imprecisiones Diagrama de Clases

### ISSUE THREAD

**Issue by FrowsyFrog** [dalbitresb12/zion-escape#3]
### Describe el problema

Mientras realizaba una pequeña inspección al diagrama de clases, pude percatarme de tres aspectos un tanto imprecisos. 
1.  La clase **Entity** es clase hija de **Sprite**. Eso es correcto; sin embargo, su enlace es de **Herencia**, cuando debería ser **Realización**, ya que en ningún momento se va a a instanciar algún objeto de Sprite (*además porque ni tiene algún constructor*).

2. Me percaté que podríamos especificar cuándo deberíamos realizar la animación. Si lo hacemos desde **Sprite** en **Draw**, los objetos (*como las rocas*), se animarán cuando no es lo que deseamos. Si es desde **Entity** puede que suceda lo mismo. Tal vez lo necesario sería hacer Virtual al **Draw** o alguna función como **Animate** , donde se anime bajo ciertas circunstancias, tanto por si es un obstáculo o por si el personaje no se está moviendo.

3. El **x** y el **y** se encuentran en **Entity**, pero en ningún momento se enlazan con la posición XY del drawingArea de Sprite. Cuando Entity vaya a realizar **Move**, se supone que va a aumentar en **x** y el **y**, pero no se va a mover porque no afecta al **drawingArea**. Tal vez podría funcionar que desde **Move**, lo que sea afectado sea algo como `drawingArea.X += dx;` sin embargo, no entendería bien la función de las variables *x* *y*. De lo contrario, tal vez sería mejor que **x** y el **y** se encuentren en **Sprite**.

4. Además, tengo una duda respecto a que **img, col, row, nCols, nRows, drawingArea** estén en *private* y nunca reciben valores, ya que ni tiene un constructor.

### Capturas de pantalla

![image](https://user-images.githubusercontent.com/73660591/98702628-a05d0400-2348-11eb-9041-163d47e38d1b.png)

**Comment by dalbitresb12** [comment]
Respondiendo a tus preguntas:

1. Lo considero irrelevante, pero para que quede claro es mejor que quede también aclarado en el diagrama de clases. El constructor nos lo olvidamos (ahora lo agregamos).

2. Podríamos agregar una propiedad `animatable` que defina si un sprite debe ser animado automáticamente durante la ejecución de la función `Draw()`.

3. La posición se puede asignar utilizando `Sprite::SetPosition();`, pero considero que podríamos convertir el atributo `drawingArea` de `private` a `protected`. Por lo tanto, este ya guardaría el X y Y del personaje y podríamos quitar los atributos correspondientes en `Entity`.

4. Falta añadir el constructor.
